### ISSUE TITLE
'list1 *read_data_cfg(char *)': cannot convert argument 1 from 'const char *' to 'char *

### ISSUE THREAD

**Issue by AndreasRef** [mrzl/ofxDarknet#1]
First of all, so exited about this addon! 

On my Windows PC (Win 10, Visual Studio 2015, of_v0.9.8) I tried to follow the instructions and build example-yolo2 and example-imagenet

I get the following error for both examples:

`'list1 *read_data_cfg(char *)': cannot convert argument 1 from 'const char *' to 'char *'`
The reference to the error is ofxDarknet.cpp line 19

**Comment by genekogan** [comment]
i get this issue in OSX as well.  going to fix this asap.  just cast it with `(char *)` to fix the problem, e.g.

    options1 = read_data_cfg((char *) datacfg.c_str() );

**Comment by genekogan** [comment]
this should be fixed now.
