### ISSUE TITLE
Build problem on macOS

### ISSUE THREAD

**Issue by HalfdanJ** [mrzl/ofxDarknet#14]
I'm trying to rebuild the darknet dylib after fixing a small error in the source code. But after building, I'm not able to call `cuda_set_device(0);`. It shows the following error at runtime: 

```
CUDA Error: CUDA driver version is insufficient for CUDA runtime version
Assertion failed: (0), function check_error, file /Users/jongejan/dev/of/addons/ofxDarknet/libs/darknet/include/cuda.c, line 39.
```

I build the library by running
```
$ cmake .
$ make
```

I'm building on a OSX 10.11.6, 
CUDA Driver Version: 8.0.53
GPU Driver Version: 10.10.14 310.42.25f02

The examples work fine before I rebuild the library. What version of the toolkit have you used for building the library?

**Comment by genekogan** [comment]
i think you have to update the GPU driver.
i was able to make successfully on OSX 10.12 with:

CUDA Driver Version: 8.0.53
GPU Driver Version: 10.12.68 355.10.05.05b16
