### ISSUE TITLE
Windows issue with Opencv

### ISSUE THREAD

**Issue by liquidzym** [mrzl/ofxDarknet#17]
not sure anyone of you has this issue under the windows
i got bunch of errors from opencv2\flann\matrix.h(69): error C2144 during the compiling
matrix.h(93): error C4430: 
opencv2\flann\matrix.h(93): error C3646
etc......

**Comment by schwittlick** [comment]
Weird, which one of the examples are you trying to run? Did you try to use the existing VS project files?

**Comment by liquidzym** [comment]
i tried both,the default existing example-yolo2,and also i did using pg to regenerate this example. both failed. weird stuff is that i'm running the existing example-yolo2,got different bunch of erros from darknet source file, the CvCapture undeclared etc.... 

are you sure this option is correct ？C/C++ -> All Options -> Compile As -> Default

i'm using vs2015 update3 version with lastest OF master

**Comment by schwittlick** [comment]
Yeah that option is necessary, so VS doesn't try to compile the CUDA kernel source files with a C++ compiler.. 

The only difference between our setups seems to be that I am using one of the OF releases (0.9.3 & 0.9.8). I am not aware if there were any changes regarding ofxOpenCv recently? Maybe it would be worth a try to use one of the releases you can download from the oF site.

**Comment by schwittlick** [comment]
@liquidzym maybe this version here is going to make it work for you. https://github.com/mrzl/ofxDarknet/issues/23

**Comment by armadillu** [comment]
Seeing the same issue on osx - it seems like it is an include confusion problem; OpenCV has "matrix.h" (opencv/include/opencv2/flann/matrix.h) but darknet also has a "matrix.h" (darknet/include/matrix.h)

**Comment by armadillu** [comment]
I ended up renaming matrix.h in darknet to matrix_.h and changing all the #includes within dakrnet to "matrix_.h" to make it work
