### ISSUE TITLE
Some important questions ....

### ISSUE THREAD

**Issue by MyVanitar** [mrzl/ofxDarknet#18]
@mrzl 
@genekogan 

Hello,

1) I want to use YOLO2 in windows. Does your repo is about this or it is YOLO1?

2) How can I train the YOLO2 on my own custom dataset (fine-tuning)? how can we see the mAP during training?

**Comment by MyVanitar** [comment]
besides, I am unable to open example-yolo2 VS2015 project as you see in the picture (load failed)

![2017-02-18_16-58-58](https://cloud.githubusercontent.com/assets/18719591/23093551/e5cb6988-f5fb-11e6-916e-6080195ef827.jpg)

**Comment by genekogan** [comment]
not sure about the windows project file -- @mrzl may know -- but about training, you are probably better off at the moment just using the [original darknet repository](http://pjreddie.com/darknet/) to train because we haven't made any convenience functions in the wrapper for doing that. possibly in the future we may try to add some support for it.

**Comment by MyVanitar** [comment]
@genekogan 

Good that somebody replied me, I was waiting for you impatiently. That error was because of missing OpenFrameworks. But anyway I have another question

Consider we have `.weights` file, `.cfg` and the rest as a result of training. 
How can I use these to make a standalone application? 
Possibly as a module or DLL file, which I could be able to write a .Net software based on that or possibly a python code or whatever. I am looking for a way to make a portable software.

**Comment by genekogan** [comment]
there is no reason to use this library without openframeworks, its purpose is to make [this darknet](http://github.com/pjreddie/darknet) work inside [openframeworks](http://openframeworks.cc). that repo will give you information on how to compile it into an executable application. answering generic questions about darknet is beyond the scope of ofxDarknet so it is better to direct those kinds of questions to the darknet google group.

**Comment by MyVanitar** [comment]
actually yes it gives an executable application, but that `.exe` file is a console application which I don't have control of it. for example I don't know how can I pass some parameters (such as detected objects coordinates or number of detected objects or classification results .. etc) between that executable and my own software which maybe should be written in VB.Net.
