### ISSUE TITLE
specifying addons_config.mk

### ISSUE THREAD

**Issue by genekogan** [mrzl/ofxDarknet#2]
in order to build projects with ofxDarknet from the project generator, we need to fill out the `addons_config.mk` file. i've gotten it to include all the darknet headers, but we still need to get it to find cuda in the search paths.  in xcode, this would be inserting `../../../addons/ofxDarknet/libs/darknet/lib/osx/ /usr/local/cuda/lib /Developer/NVIDIA/CUDA-8.0/lib/` into the library search path and runpath search path in the build settings.

**Comment by schwittlick** [comment]
for Windows 10 the project generator works out of the box, the settings described here https://github.com/mrzl/ofxDarknet#setup are necessary to be done manually as this is not covered via the project generator. all includes are fine..

let me know here when the osx workflow with the adjusted addons_config.mk is working and i will cross-check if it broke something on windows.. i dont use osx so i unfortunately can't test anything. maybe @BildPeter can be your partner in crime on this?

**Comment by genekogan** [comment]
this is now building properly from project generator in OSX, as of commit c8a903461597e6444121478f01c8461eeb94fcca

**Comment by jkruseAUT** [comment]
unfortunately I get build errors:

Win10 x64, VS2015, Cuda 8.0, ofxDarknet. In addition to https://github.com/mrzl/ofxDarknet#setup do I need to install OpenCV?   What about the issue that ofxOpenCV does not build on Win10 - does this have any impact?
