### ISSUE TITLE
GPU mode issue

### ISSUE THREAD

**Issue by DougLilliequist** [mrzl/ofxDarknet#24]
It seems that the plugin is not using the GPU/CUDA due to sluggish performance and only one CPU running on 100%. But when I'm running the standalone darknet app, it runs flawlessly!

I tried the branch that allows you (from what I understand) to run in GPU mode. But when I compile, the app breaks and the output is following:

'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Users\B-ReelLDN\Desktop\of_v0.9.8_vs_release\apps\myApps\DarkNetToNodeV1\bin\DarkNetToNodeV1_debug.exe'. Symbols loaded.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\ntdll.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\kernel32.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\KernelBase.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\ws2_32.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\sechost.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\opengl32.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\rpcrt4.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\msvcrt.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\advapi32.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\user32.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\gdi32.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\win32u.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\msvcp140d.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\concrt140d.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\gdi32full.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\shell32.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\cfgmgr32.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\vcruntime140d.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbased.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Users\B-ReelLDN\Desktop\of_v0.9.8_vs_release\apps\myApps\DarkNetToNodeV1\bin\FreeImage.dll'. Module was built without symbols.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\windows.storage.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\combase.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbase.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\glu32.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\bcryptprimitives.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\ddraw.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\powrprof.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\vcomp120.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\shlwapi.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\dciman32.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\kernel.appcore.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\SHCore.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\profapi.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\ole32.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\oleaut32.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\msvcp_win.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\crypt32.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\msasn1.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Users\B-ReelLDN\Desktop\of_v0.9.8_vs_release\apps\myApps\DarkNetToNodeV1\bin\fmodex64.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\IPHLPAPI.DLL'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\winmm.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Users\B-ReelLDN\Desktop\of_v0.9.8_vs_release\apps\myApps\DarkNetToNodeV1\bin\pthreadVC2.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\cudart64_80.dll'. Module was built without symbols.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\cublas64_80.dll'. Module was built without symbols.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\curand64_80.dll'. Module was built without symbols.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\winmmbase.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\msvcr100.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\wsock32.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\msacm32.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\imm32.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\uxtheme.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\dwmapi.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\msctf.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\nvoglv64.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\setupapi.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\wtsapi32.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\version.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\devobj.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\wintrust.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\ntmarta.dll'. Cannot find or open the PDB file.
The thread 0x4388 has exited with code 0 (0x0).
The thread 0x3094 has exited with code 0 (0x0).
The thread 0x63c has exited with code 0 (0x0).
The thread 0x14c4 has exited with code 0 (0x0).
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\winsta.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\clbcatq.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Program Files (x86)\Blackmagic Design\Blackmagic Desktop Video\DeckLinkAPI64.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\msvcp120.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\msvcr120.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\nvcuda.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\nvfatbinaryLoader.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\nvapi64.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\dxgi.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\mswsock.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\wshqos.dll'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\WSHTCPIP.DLL'. Cannot find or open the PDB file.
'DarkNetToNodeV1_debug.exe' (Win32): Loaded 'C:\Windows\System32\wship6.dll'. Cannot find or open the PDB file.
Exception thrown at 0x00007FFF69CC90D3 (nvcuda.dll) in DarkNetToNodeV1_debug.exe: 0xC0000005: Access violation reading location 0x0000000082FBF000.

The program '[3168] DarkNetToNodeV1_debug.exe' has exited with code 0 (0x0).

Is there anything that I have missed in the setup or do I have to take an extra step to allow the Openframeworks app to utilize the GPU/CUDA?

Best

Doug

**Comment by DougLilliequist** [comment]
*UPDATE* Solved with checking in download 'Microsoft Symbol Servers', but now I get a crash due to LNK2019 issue!

**Comment by DougLilliequist** [comment]
UPDATE Solved the linker issue as well, but the app is still running super slow and does not appear to use the GPU

**Comment by schwittlick** [comment]
Please install CUDA and add CUDA to the project as I described in the README
