### ISSUE TITLE
Eclipse Problem

### ISSUE THREAD

**Issue by cevatbostancioglu** [mrzl/ofxDarknet#29]
Hello, i included ofxDarknet with ofxGui in eclipse on linux(ubuntu) but nothing seems work

![image](https://user-images.githubusercontent.com/6525009/27435303-713143c0-5764-11e7-8a78-af8ebc4e48fc.png)

so do you guys have any idea ? i am new to openframeworks.

**Comment by genekogan** [comment]
eclipse can't find "ofMain.h" which means you are having issues with openframeworks not ofxDarknet. please get comfortable with openframeworks first, then try to work with ofxDarknet. try [http://openframeworks.cc/learning/](http://openframeworks.cc/learning/).
