### ISSUE TITLE
GPU=1 make fails

### ISSUE THREAD

**Issue by Dahlasam** [mrzl/ofxDarknet#34]
While CPU make succeeds and darknet works well, the GPU=1 make to enable GPU support fails.
I get the following compiling errors:

`ptxas /tmp/tmpxft_00001c51_00000000-15_convolutional_kernels.compute_30.ptx, line 115; error   : Call has wrong number of parameters
ptxas /tmp/tmpxft_00001c51_00000000-15_convolutional_kernels.compute_30.ptx, line 144; error   : Call has wrong number of parameters
ptxas /tmp/tmpxft_00001c51_00000000-15_convolutional_kernels.compute_30.ptx, line 227; error   : Call has wrong number of parameters
ptxas /tmp/tmpxft_00001c51_00000000-15_convolutional_kernels.compute_30.ptx, line 257; error   : Call has wrong number of parameters
ptxas /tmp/tmpxft_00001c51_00000000-15_convolutional_kernels.compute_30.ptx, line 341; error   : Call has wrong number of parameters
ptxas /tmp/tmpxft_00001c51_00000000-15_convolutional_kernels.compute_30.ptx, line 361; error   : Call has wrong number of parameters
ptxas /tmp/tmpxft_00001c51_00000000-15_convolutional_kernels.compute_30.ptx, line 379; error   : Call has wrong number of parameters
ptxas /tmp/tmpxft_00001c51_00000000-15_convolutional_kernels.compute_30.ptx, line 399; error   : Call has wrong number of parameters
ptxas fatal   : Ptx assembly aborted due to errors
Makefile:91: recipe for target 'obj/convolutional_kernels.o' failed
make: *** [obj/convolutional_kernels.o] Error 255
`
System details:
OS: Ubuntu 16.04 x64
GPU: Nvidia GTX 1060
nvidia-smi output:

`+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.81                 Driver Version: 384.81                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 106...  Off  | 00000000:01:00.0  On |                  N/A |
|  0%   43C    P8     7W / 156W |   5955MiB /  6069MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1042      G   /usr/lib/xorg/Xorg                           197MiB |
|    0      1839      G   compiz                                        77MiB |
|    0      2923      G   ...-token=5D46E4CA8207FFF70E348E0EA2F3C753   108MiB |
|    0     28788      C   /home/sami/miniconda2/bin/python            5567MiB |
+-----------------------------------------------------------------------------+`

Any suggestions? What CUDA and CUDNN versions are supported?

Thanks,
Sami
--

**Comment by 4F2E4A2E** [comment]
@Dahlasam why is it closed? Did you solved it?

**Comment by Dahlasam** [comment]
Hi,

Yes - the issue related to local configuration gap only in my system and I
got the CUDA and cuDNN working after ~/.bashrc update. And I mistakenly
created this issue in ofxDarknet while I faced the problem originally with
baseline darknet.

The same topic issue in darknet by @AnanasPie:
https://github.com/pjreddie/darknet/issues/230

BRs,
Sami
--

**Comment by 4F2E4A2E** [comment]
Thanks man!

**Comment by bit-scientist** [comment]
Hi @Dahlasam, please could you show me how to update ~/.bashrc? 
I'm also facing similar issue in another project based on this repo. PLease refer to [here](https://github.com/qiaoguan/Fall-detection/issues/10)
