### ISSUE TITLE
issue with new version cuda 9.1

### ISSUE THREAD

**Issue by pampanelson** [mrzl/ofxDarknet#37]
after installed cuda 9.1 toolkit , no extra code adding ,just try build and got errors:

dyld: Library not loaded: @rpath/libcublas.8.0.dylib
  Referenced from: /Applications/of_v0.9.8_osx_release/addons/ofxDarknet/libs/darknet/lib/osx/libdarknetOSX.dylib
  Reason: image not found

same issue with file "libcurand.8.0.dylib" and "libcusparse.8.0.dylib"

I found "libcublas.9.1.dylib" in /usr/local/cuda/lib , duplicated it and changed name to "libcublas.8.0.dylib" to remove error.same to rest files.

I'm not sure if this hacking works before doing something real yet.

is the 8.0 version of cuda are pre defined  in the addon ? where can I change it to newest 9.1 ?

thanks !

**Comment by schwittlick** [comment]
yes the static library for osx is compiled to use cuda8. if you wanna use darknet, better change to cuda8 again for now.. or you can compile a cuda9 static library as its described here https://github.com/mrzl/ofxDarknet#building-the-library-from-source

im happy to receive a pull request and figure this out
