### ISSUE TITLE
trying to run examples but they close immediately after opening

### ISSUE THREAD

**Issue by ghost** [mrzl/ofxDarknet#39]
Hi, 

I am trying to build the examples that come with the addon in VS2015, OF0.9.8 and windows 10. The solution builds, but when trying to run the example either on Debug or Release mode for x64, the console window opens shows some output and closes immediately after starting to load weights. The following is the debugging output. Any help or advice to get darknet working with openframeworks would be greatly appreciated. Thank you.

'example-imagenet.exe' (Win32): Loaded '\of_v0.9.8_vs_release\addons\ofxDarknet\example-imagenet\bin\example-imagenet.exe'. Module was built without symbols.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\ntdll.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\kernel32.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\KernelBase.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbase.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\vcruntime140.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\msvcp140.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\user32.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\win32u.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\opengl32.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Users\paulo\Documents\of_v0.9.8_vs_release\addons\ofxDarknet\example-imagenet\bin\FreeImage.dll'. Module was built without symbols.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\gdi32.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\msvcrt.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\ws2_32.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\gdi32full.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\advapi32.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\vcomp120.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\rpcrt4.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\msvcp_win.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\sechost.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\shell32.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\cfgmgr32.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\glu32.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\SHCore.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\combase.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\bcryptprimitives.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\windows.storage.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\shlwapi.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\kernel.appcore.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\profapi.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\powrprof.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\fltLib.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\ole32.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\oleaut32.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\crypt32.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\winmm.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\msasn1.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Users\paulo\Documents\of_v0.9.8_vs_release\addons\ofxDarknet\example-imagenet\bin\fmodex64.dll'. Cannot find or open the PDB file.
'example-imagenet.exe' (Win32): Loaded 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\cudart64_80.dll'. Module was built without symbols.
'example-imagenet.exe' (Win32): Loaded 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\cublas64_80.dll'. Module was built without symbols.
'example-imagenet.exe' (Win32): Loaded 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\curand64_80.dll'. Module was built without symbols.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\wsock32.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\winmmbase.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\winmmbase.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Unloaded 'C:\Windows\System32\winmmbase.dll'
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\winmmbase.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Unloaded 'C:\Windows\System32\winmmbase.dll'
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\msacm32.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\imm32.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\uxtheme.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\dwmapi.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\msctf.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\DriverStore\FileRepository\nvrzi.inf_amd64_8b6520f7e1d6ff54\nvdlistx.dll'. Cannot find or open the PDB file.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\version.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Unloaded 'C:\Windows\System32\version.dll'
'example-imagenet.exe' (Win32): Unloaded 'C:\Windows\System32\DriverStore\FileRepository\nvrzi.inf_amd64_8b6520f7e1d6ff54\nvdlistx.dll'
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\DriverStore\FileRepository\nvrzi.inf_amd64_8b6520f7e1d6ff54\nvoglv64.dll'. Cannot find or open the PDB file.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\setupapi.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\version.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\wtsapi32.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\devobj.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\wintrust.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\ntmarta.dll'. Symbols loaded.
The thread 0x2190 has exited with code 0 (0x0).
The thread 0x8554 has exited with code 0 (0x0).
The thread 0x8c34 has exited with code 0 (0x0).
The thread 0x5e94 has exited with code 0 (0x0).
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\nvspcap64.dll'. Cannot find or open the PDB file.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\psapi.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\winhttp.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\winsta.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\dxgi.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\d3d11.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\ResourcePolicyClient.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Unloaded 'C:\Windows\System32\ResourcePolicyClient.dll'
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\DriverStore\FileRepository\nvrzi.inf_amd64_8b6520f7e1d6ff54\nvdlistx.dll'. Cannot find or open the PDB file.
'example-imagenet.exe' (Win32): Unloaded 'C:\Windows\System32\DriverStore\FileRepository\nvrzi.inf_amd64_8b6520f7e1d6ff54\nvdlistx.dll'
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\DriverStore\FileRepository\nvrzi.inf_amd64_8b6520f7e1d6ff54\nvldumdx.dll'. Cannot find or open the PDB file.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\imagehlp.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\cryptsp.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\rsaenh.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\bcrypt.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\cryptbase.dll'. Symbols loaded.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\DriverStore\FileRepository\nvrzi.inf_amd64_8b6520f7e1d6ff54\nvwgf2umx.dll'. Cannot find or open the PDB file.
'example-imagenet.exe' (Win32): Loaded 'C:\Program Files\NVIDIA Corporation\Ansel\Tools\NvCameraWhitelisting64.dll'. Cannot find or open the PDB file.
'example-imagenet.exe' (Win32): Unloaded 'C:\Program Files\NVIDIA Corporation\Ansel\Tools\NvCameraWhitelisting64.dll'
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\nvapi64.dll'. Cannot find or open the PDB file.
The thread 0x4ae8 has exited with code 0 (0x0).
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\nvcuda.dll'. Cannot find or open the PDB file.
'example-imagenet.exe' (Win32): Loaded 'C:\Windows\System32\nvfatbinaryLoader.dll'. Cannot find or open the PDB file.
The thread 0x8bf0 has exited with code 0 (0x0).
The thread 0x7e54 has exited with code 0 (0x0).
The thread 0x8fd4 has exited with code 0 (0x0).
The thread 0x7fd0 has exited with code 0 (0x0).
The thread 0x51f4 has exited with code 0 (0x0).
The thread 0x355c has exited with code 0 (0x0).
The thread 0x7fa8 has exited with code 0 (0x0).
The thread 0x15c0 has exited with code 0 (0x0).
The thread 0x2d4c has exited with code 0 (0x0).
The thread 0xbec has exited with code 0 (0x0).
The thread 0x27ec has exited with code 0 (0x0).
The thread 0x446c has exited with code 0 (0x0).
The program '[36784] example-imagenet.exe' has exited with code 0 (0x0).

**Comment by ratmother** [comment]
Did you manage to fix this?
