### ISSUE TITLE
yolo9000 update net = parse_network_cfg... BAD ACCESS

### ISSUE THREAD

**Issue by AndreasRef** [mrzl/ofxDarknet#8]
Tried building the newest version of example-yolo2 with yolo9000.weights but running into this error... Any idea why? Also tried changing the paths to relative paths, without any result. 

![screen shot 2017-01-19 at 15 29 04](https://cloud.githubusercontent.com/assets/9645568/22110461/11628a20-de5c-11e6-98ce-c7fa2bc83e72.png)

**Comment by genekogan** [comment]
check out the bottom of the cfg file `yolo9000.cfg`, lines `tree` and `map`. try changing to:

    tree=../../../data/cfg/9k.tree
    map=../../../data/cfg/coco9k.map

**Comment by AndreasRef** [comment]
Seems like that helped, but now I get this error:

`Couldn't open file: data/cfg/9k.names`

**Comment by genekogan** [comment]
it's not finding the file. make sure the paths are set correctly. if you are referencing from the file, just switch to `ofToDataPath( "cfg/9k.names" )` and make sure you have that file in there.

**Comment by AndreasRef** [comment]
`cfg/9k.names` is not referenced from the ofApp.cpp file only the following are

```
    std::string datacfg = ofToDataPath( "cfg/combine9k.data" );
    std::string cfgfile = ofToDataPath( "cfg/yolo9000.cfg" );
    std::string weightfile = ofToDataPath( "yolo9000.weights
```

`9k.names` is just placed in `/cfg`, not sure how (or where) to set its path correctly.

**Comment by genekogan** [comment]
go to `combine9k.data` and either hardcode the path or `../../../data/cfg/9k.names` should work. or you can switch to the osx branch which lets you pass the names file manually via ofApp. we'll merge those soon.

**Comment by AndreasRef** [comment]
Editing the `combine9k.data` did the trick, thanks!

**Comment by smalleight17** [comment]
Hey I'm kind of having the same issue here... with the last two line in the yolo9000.cfg file the parse_network_cfg function couldn't really parse the file... visual studio would give me unhandled exception error... if I remove those two lines it compiles fine, but I'm not supposed to do that right?

Also since now the ofxDarknet::init function only takes in 3 parameters now, do we still need combine9k.data anymore? If yes where do I put it?
